### PR TITLE
feat: add update window constraints

### PR DESCRIPTION
**Pull request by jsmylnycky**
@Acekorneya I ran through a couple checks locally to ensure the logic behaves as expected, but you might want to give it a double check as well

### CODE REVIEW

**Comment by jsmylnycky** [comment]
Hey @Acekorneya Any chance of getting a review and hopefully a merge of this please? :) Thanks!

**Review by Acekorneya — APPROVED** [review]
Yeah Looks Good To me from what i've seen it should work but i'll give it a test right now in a bit before i push it to the docker

**Comment by Acekorneya** [comment]
And THANK YOU btw for doing this for me really Appreciate it awesome idk how to add you to the contribution etc as im a noob still on githhub lol..

**Comment by jsmylnycky** [comment]
No worries, happy to help :)

**Pull request merged**
